version: '3'
services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #placeholder -> hogy ne tudjuk felülirni
      - .:/app # kint az /app/node_modules bentre a /app-ra
  tests:
    build:
      context: . 
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]